doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_sqlite'
        charset: utf8
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Enraged\Application:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/application'
                prefix: 'Enraged\Application'
            Enraged\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/domain'
                prefix: 'Enraged\Domain'
            Enraged\Infrastructure:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/infrastructure'
                prefix: 'Enraged\Infrastructure'