version: "3.3"
services:
  application:
    container_name: application
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3160:3160"
