services:
    # INFRASTRUCTURE/CALENDAR
    Enraged\Infrastructure\Calendar\CalendarInterface:
        class: 'Enraged\Infrastructure\Calendar\InMemoryCalendar'

    # INFRASTRUCTURE/HTTP
    Enraged\Infrastructure\HTTP\Client\HttpClientInterface:
        class: 'Enraged\Infrastructure\HTTP\Client\InMemoryHttpClient'
        public: true
        autowire: true